"""empty message

Revision ID: 4b6d45fe54eb
Revises: cf39e7c0c16a
Create Date: 2020-04-04 09:33:42.994479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b6d45fe54eb'
down_revision = 'cf39e7c0c16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('is_seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_desc', sa.String(length=120), nullable=True))
    op.add_column('artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'website_link')
    op.drop_column('artist', 'seeking_desc')
    op.drop_column('artist', 'is_seeking_venue')
    # ### end Alembic commands ###
