"""empty message

Revision ID: 7a2b5076503f
Revises: 28d58d1c5109
Create Date: 2020-03-28 20:32:29.040513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2b5076503f'
down_revision = '28d58d1c5109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.Date(), nullable=True))
    op.drop_column('shows', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('time', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
