"""empty message

Revision ID: 834163195c21
Revises: 5414ef8421c3
Create Date: 2020-03-21 19:20:57.893529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '834163195c21'
down_revision = '5414ef8421c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_venue_id_fkey', 'artist', type_='foreignkey')
    op.drop_column('artist', 'venue_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('artist_venue_id_fkey', 'artist', 'venue', ['venue_id'], ['id'])
    # ### end Alembic commands ###
