"""empty message

Revision ID: cf39e7c0c16a
Revises: 7a2b5076503f
Create Date: 2020-03-30 20:03:55.864344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf39e7c0c16a'
down_revision = '7a2b5076503f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.String(length=1000), nullable=True))
    op.add_column('venue', sa.Column('is_seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent_desck', sa.String(length=1000), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website_link')
    op.drop_column('venue', 'seeking_talent_desck')
    op.drop_column('venue', 'is_seeking_talent')
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###
